spring:
  datasource:
    url: jdbc:mysql://localhost:3306/line_integration
    username: username
    password: password
    driverClassName: com.mysql.jdbc.Driver
flyway:
  enabled: false
logging.level:
  root: WARN
  jp.co.tdc: INFO
line:
  channelId: 9999999999
  pushRatePerMinute: 1
